### ISSUE TITLE
Number of characters displayed on the autocompletion box

### ISSUE THREAD

**Issue by danpal96** [jupyter-lsp/jupyterlab-lsp#1002]
## Elevator Pitch
I would like a way to control the number of characters displayed on the autocompletion box

## Motivation
With jupyterlab-lsp 5.0.0 the autocompletion box does not diplay a lot of characters:
![image](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/37080389/94943fe3-94c7-4bae-abd2-ed48229778b7)
Comparison without  jupyterlab-lsp:
![image](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/37080389/a3eb29c6-7444-49e3-918f-8a78620e4043)

**Comment by krassowski** [comment]
Thanks for opening the issue. This is a bug with width heuristic, and appears related to a previous issue #995.

**Comment by danpal96** [comment]
Is the fix merged in jupyterlab-lsp=5.1.0 jupyter-lsp=2.2.4, I'm still having the problem of too little space

![image](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/37080389/a38adc98-7ea3-4267-9b63-ae3c79ae66f6)

If it needs to cut down the characters I would prefer that it cuts at the start instead of the end
