### ISSUE TITLE
Could not determine npm prefix: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by JulianSMoore** [jupyter-lsp/jupyterlab-lsp#1004]
I'm not a dev so I hope the following suffices to be useful:

Windows 10
IPython          : 8.16.1
ipykernel        : 6.25.2
ipywidgets       : 8.1.1
jupyter_client   : 8.4.0
jupyter_core     : 5.4.0
jupyter_server   : 2.8.0
jupyterlab       : 4.0.7
nbclient         : 0.8.0
nbconvert        : 7.9.2
nbformat         : 5.9.2
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.11.2

with jupyterlab-lsp==5.0.0 jupyter-lsp==2.2.0 python-lsp-server[all]

on startup, the console kept saying "Could not determine npm prefix: [WinError 2] The system cannot find the file specified"

It's not that npm is missing, it's because WIndows isn't Linux; see [here](https://stackoverflow.com/questions/14680733/how-to-install-npm-package-from-python-script/50045443#50045443)

I resolved the problem for myself: in C:\Users\Julian\anaconda3\envs\PlainPY\Lib\site-packages\jupyter_lsp\types.py

In the class LanguageServerManagerAPI, change _npm_prefix to be

    def _npm_prefix(self):
        try:
            return (
                subprocess.run(["npm.cmd", "prefix", "-g"], check=True, capture_output=True)
                .stdout.decode("utf-8")
                .strip()
            )
        except Exception as e:  # pragma: no cover
            self.log.warn(f"Could not determine npm prefix: {e}")

i.e. add ".cmd" to npm: the error wasn't saying the prefix couldn't be found, but rather it couldn't invoke npm in the first place,

Obviously that's not a fix for everyone, it's windows specific.

**Comment by krassowski** [comment]
I believe this should be solved with https://github.com/jupyter-lsp/jupyterlab-lsp/pull/955 which will be available in the next jupyter-lsp version.

**Comment by JulianSMoore** [comment]
Great. Strange that that issue wasn't obvious when I googled it first, but still -- great. Thx.

**Comment by waysbg** [comment]
> **[JulianSMoore](/JulianSMoore) ** commented

Tnks man, it helped, i mean adding .cmd to this part ....["npm.cmd", "prefix", "-g"].... as you have explained. 
Tnks!!!

**Comment by WKQ9411** [comment]
Thanks for the solution, it really works!

**Comment by SpezialK71** [comment]
This fixed an annoying issue I'd been having for months.

**Thanks**!

**Comment by ygwang1** [comment]
Thanks!!!

**Comment by jtyoui** [comment]
Thanks!!!

**Comment by alanyagger** [comment]
> I'm not a dev so I hope the following suffices to be useful:
> 
> Windows 10 IPython : 8.16.1 ipykernel : 6.25.2 ipywidgets : 8.1.1 jupyter_client : 8.4.0 jupyter_core : 5.4.0 jupyter_server : 2.8.0 jupyterlab : 4.0.7 nbclient : 0.8.0 nbconvert : 7.9.2 nbformat : 5.9.2 notebook : not installed qtconsole : not installed traitlets : 5.11.2
> 
> with jupyterlab-lsp==5.0.0 jupyter-lsp==2.2.0 python-lsp-server[all]
> 
> on startup, the console kept saying "Could not determine npm prefix: [WinError 2] The system cannot find the file specified"
> 
> It's not that npm is missing, it's because WIndows isn't Linux; see [here](https://stackoverflow.com/questions/14680733/how-to-install-npm-package-from-python-script/50045443#50045443)
> 
> I resolved the problem for myself: in C:\Users\Julian\anaconda3\envs\PlainPY\Lib\site-packages\jupyter_lsp\types.py
> 
> In the class LanguageServerManagerAPI, change _npm_prefix to be
> 
> ```
> def _npm_prefix(self):
>     try:
>         return (
>             subprocess.run(["npm.cmd", "prefix", "-g"], check=True, capture_output=True)
>             .stdout.decode("utf-8")
>             .strip()
>         )
>     except Exception as e:  # pragma: no cover
>         self.log.warn(f"Could not determine npm prefix: {e}")
> ```
> 
> i.e. add ".cmd" to npm: the error wasn't saying the prefix couldn't be found, but rather it couldn't invoke npm in the first place,
> 
> Obviously that's not a fix for everyone, it's windows specific.

thanks a lot  this problem has been confusing me for several weeks
