### ISSUE TITLE
tab-key code completion with julia

### ISSUE THREAD

**Issue by daviehh** [jupyter-lsp/jupyterlab-lsp#1009]
## Description

Julia allows for unicode in e.g. variable names, entered with latex code or similar: [ref](https://docs.julialang.org/en/v1/manual/unicode-input/).
For example, \Delta + <kbd>tab</kbd> key will transform it to Δ in the julia REPL console or in the jupyter notebook without jupyterlab-lsp installed.

However, with jupyterlab-lsp enabled, the jupyter notebook/lab will not do the transform to unicode, but suggest other `/`-commands

## Reproduce

1. Enter \Delta in a cell with julia (IJulia.jl) kernel
2. Pop-up suggests codes related to \Delta, but does not do the replacement to Δ

## Expected behavior

\Delta + <kbd>tab</kbd> gives Δ

## Context

- Operating System and version: macos, 14.1
- Browser and version: chrome 120.0.6099.5 (Official Build) beta (arm64)
- JupyterLab version: 4.0.8
- Language server and version: julia, v1.10.0

<details><summary>Required: installed server extensions</summary>
<pre>
jupyter_lsp enabled
    - Validating jupyter_lsp...
Package jupyter_lsp took 0.0071s to import
A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      jupyter_lsp 2.2.0 OK
    jupyter_server_mathjax enabled
    - Validating jupyter_server_mathjax...
Package jupyter_server_mathjax took 0.0008s to import
      jupyter_server_mathjax  OK
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
Package jupyter_server_terminals took 0.0038s to import
      jupyter_server_terminals 0.4.4 OK
    jupyterlab enabled
    - Validating jupyterlab...
Package jupyterlab took 0.0281s to import
      jupyterlab 4.0.8 OK
    jupytext enabled
    - Validating jupytext...
Package jupytext took 0.0516s to import
      jupytext 1.15.2 OK
    nbclassic enabled
    - Validating nbclassic...
Package nbclassic took 0.0019s to import
A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      nbclassic 1.0.0 OK
    nbdime enabled
    - Validating nbdime...
Package nbdime took 0.0076s to import
      nbdime 3.2.1 OK
    notebook enabled
    - Validating notebook...
Package notebook took 0.0000s to import
      notebook 7.0.6 OK
    notebook_shim enabled
    - Validating notebook_shim...
Package notebook_shim took 0.0000s to import
A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      notebook_shim  OK
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
        jupyterlab-jupytext v1.3.9 enabled  (python, jupytext)
        nbdime-jupyterlab v2.2.0 enabled 
        @jupyter-notebook/lab-extension v7.0.6 enabled OK
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
Paste the output from your browser JavaScript console replacing the text in here.

To learn how to open the developer tools in your browser:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser
If too many messages accumulated after many hours of working in JupyterLab,
consider refreshing the window and then reproducing the bug to reduce the noise in the logs.

</pre>
</details>

**Comment by krassowski** [comment]
Thank you for opening the issue. This will be fixed in the next patch release. In the meantime you could try disabling 'pre-filter matches' option:

![Screenshot from 2023-11-20 16-18-23](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/5832902/08ea3b61-aafc-460e-942c-e256bb13e488)
