### ISSUE TITLE
custom --jp-editor-mirror-lsp-highlight-background-color value

### ISSUE THREAD

**Issue by vchabaux** [jupyter-lsp/jupyterlab-lsp#1042]
Hello, 

I don't understand how to set a custom color for "--jp-editor-mirror-lsp-highlight-background-color".

Thank you very much!

**Comment by krassowski** [comment]
Are you developing a theme? Something like:

```css
:root {
  /* highlight */
  --jp-editor-mirror-lsp-highlight-background-color: color-mix(
    in srgb,
    red 25%,
    transparent
  );
```

should work based on what is defined in:

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/fdd3affdf07d8077c19433ef299e1d0fa777818e/packages/jupyterlab-lsp/style/variables/base.css#L1-L7

Of note, in [JupyterLab 4.1](https://fosstodon.org/@krassowski/111816186128588086) you will be able to include it in `custom.css` (see https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#v4-1)

**Comment by vchabaux** [comment]
Thanks a lot!

I understand now that it's not jupyterlab-lsp related at all, but I didn't know how themes worked in jupyter. This new option in version 4.1 is awesome. It works perfectly!

Thanks again and sorry for the inconvenience!

**Comment by vchabaux** [comment]
Fixed
