### ISSUE TITLE
Is @krassowski/jupyterlab-lsp still need to be installed?

### ISSUE THREAD

**Issue by linxiaohui** [jupyter-lsp/jupyterlab-lsp#1058]
When I using JupyterLab 3.X I used to 

`jupyter labextension install  @krassowski/jupyterlab-lsp`

is this still needed when using JupyetrLab 4.x?

When I execute this, it says we should use pip to install jupyetrlab-lsp; is this same as `jupyter labextension install  @krassowski/jupyterlab-lsp`

**Comment by krassowski** [comment]
Hi @linxiaohui no, you should NOT install the _source_ extension using `labextension install`.
You should either use `pip` or `conda` to install a _prebuilt_ `jupyterlab-lsp`.

This is true in general of JupyterLab 3+. If you would like to learn more about the difference between source and prebuilt extensions see:
- https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#overview-of-extensions
- https://github.com/jupyterlab/jupyterlab/issues/10554

Closing as answered.
