### ISSUE TITLE
GitHub release artifacts are not separate for jupyter-lsp and jupyterlab-lsp

### ISSUE THREAD

**Issue by lahwaacz** [jupyter-lsp/jupyterlab-lsp#1072]
Both [jupyter-lsp-2.2.4.tar.gz](https://github.com/jupyter-lsp/jupyterlab-lsp/archive/refs/tags/jupyter-lsp-2.2.4.tar.gz) and [(jupyterlab-lsp) v5.1.0.tar.gz](https://github.com/jupyter-lsp/jupyterlab-lsp/archive/refs/tags/v5.1.0.tar.gz) release artifacts have precisely the same structure - they include the whole git repository at the point of the release.

On the other hand, the [jupyter-lsp-2.2.4.tar.gz](https://files.pythonhosted.org/packages/8f/34/c7394087933293e28d6330e665272070037876ceb94e4d84a7464da565e9/jupyter-lsp-2.2.4.tar.gz) file on PyPI contains just the [python_packages/jupyter_lsp](https://github.com/jupyter-lsp/jupyterlab-lsp/tree/main/python_packages/jupyter_lsp) directory and [jupyterlab-lsp-5.1.0.tar.gz](https://files.pythonhosted.org/packages/b8/49/b6bc55457ebac72928c9db6e5c23c6e0a1d3a5640fc4b4abb4275f10ef7c/jupyterlab-lsp-5.1.0.tar.gz) on PyPI contains just the [python_packages/jupyterlab_lsp](https://github.com/jupyter-lsp/jupyterlab-lsp/tree/main/python_packages/jupyterlab_lsp) directory.

Can you clarify what is the point of each different source release? What happens when I build a package from the top level directory of the git repository? Does it build both Python packages at once? Is there anything else being built?

**Comment by krassowski** [comment]
These archives are auto-generated by GitHub. We do not have control over them as far as I know.

> What happens when I build a package from the top level directory of the git repository

I think nothing much as this is not setup as a proper Python monorepo right now. You would need to build each package separately. If you wish to do so, currently this is done by these lines on CI:

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/b159ae2736b26463d8cc8f0ef78f4b2ce9913370/.github/workflows/job.test.yml#L179-L186

but subject to change to more modern tooling at some point
