### ISSUE TITLE
Auto completion do not need to click `Tab`

### ISSUE THREAD

**Issue by Firestar-Reimu** [jupyter-lsp/jupyterlab-lsp#1083]
## Elevator Pitch

show the auto-completion box following the cursor

## Motivation

visual-studio-code and spyder can show the auto-completion box whenever you type and do not need to click the tab button every time you want to complete.

## Design Ideas

![图片](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/65082432/e8165b88-55c7-4734-8567-bd36f0585101)

**Comment by krassowski** [comment]
You need to enable it in the settings. Temporarily there are two boxes in two settings panels which needs to be checked.

**Comment by Firestar-Reimu** [comment]
Thanks, One is `Code Completion` >> `Continuous hinting`, the other is `Code Completion` >> `Enable autocompletion.`

Maybe these 2 menus which have the same name should be combined?

Also, the timeout should not be 0? if you want to have a quicker reply it can be set to 1 but not 0.
