### ISSUE TITLE
detect Type/Literal Type failing?

### ISSUE THREAD

**Issue by linlol** [jupyter-lsp/jupyterlab-lsp#1106]
## What are you trying to do?

![image](https://github.com/user-attachments/assets/b2550577-79ce-4be5-8e8d-8e5aa7e715a9)

As above, looks like type-hint failed to be detected by LSP for both Pylance and Ruff, while ruff shall support to detect this (since I can get this from VSCode

## How is it done today, and what are the limits of current practice?

This is also what I am checking, is there any existing setting that supports for this type-safety checking, and may I know the major difficulty of not implementing this if not.

## What is new in your approach and why do you think it will be successful?
Since it work in other LSP based IDE so I guess it is feasible, haven't check the detail, would check ruff lsp in detail.

## Who cares? If you are successful, what difference will it make?
For those who use Jupyter in development, we have a lot of code initiated, developed and tested in running JupyterHub (and copied to our working project before commited)

## What are the risks?
No risk as what I can see
## How much will it cost?
It shall be free

## How long will it take?
I have no idea! Need to have a look in detail.

**Comment by krassowski** [comment]
This absolutely works in with `pylsp` server and [`pylsp-mypy`](https://github.com/python-lsp/pylsp-mypy) installed:

![image](https://github.com/user-attachments/assets/c74c2621-33ce-4b4d-9ef6-ef790b004a5b)

I think it also works with the pyright server.

Currently jupyterlab-lsp has no out-of-the-box support for pylance nor ruff language servers. Were you using [`python-lsp-ruff`](https://github.com/python-lsp/python-lsp-ruff) or the `ruff-ls?

In an case, this is not a problem with jupyterlab-lsp but with the language server of choice not returning what you want :)

**Comment by linlol** [comment]
thanks @krassowski and sorry about this... 

I would take a further look , thanks

**Comment by linlol** [comment]
Hi @krassowski , a quick follow up 

Yes you are correct that mypy lsp can help for type checking.

For ruff side, what we did is in jupyterlab config json, in serversettings

Set pylsp.plugins.ruff.enabled as true,
And set config file path, seems that this provides limited linting support by ruff

**Comment by linlol** [comment]
Mark as closed since it is already implemented, also, it shall be more like an issue about how to choose lsp server
