### ISSUE TITLE
Use mime types from server spec for language detection

### ISSUE THREAD

**Issue by bollwyvl** [jupyter-lsp/jupyterlab-lsp#190]
## Elevator Pitch

If available, use the mime types provided by specs to detect languages rather than (just) string parsing or lookup tables.

## Motivation

#189 points out a case where a language doesn't (yet) have a well-defined language type (https://github.com/robots-from-jupyter/robotkernel/issues/40).

## Design Ideas

In addition to the [lookup table](https://github.com/krassowski/jupyterlab-lsp/blob/master/packages/jupyterlab-lsp/src/adapters/jupyterlab/jl_adapter.ts#L92) of languages, detection should also consult the [server spec](https://github.com/krassowski/jupyterlab-lsp/blob/master/py_src/jupyter_lsp/schema/schema.json#L137) mime types. 

It may be that we need to open this up even wider, and allow for server specs to offer the full rosetta stone of `mimetype`, `codemirror_mode` and `name`, depending on how much information might be available.

**Comment by krassowski** [comment]
Agreed, this the right thing to do. However, we need to adjust the schema slightly as we need mimetype → language mapping, as one server can handle multiple languages.

**Comment by krassowski** [comment]
I believe we already do that, so closing as completed. Any future enhancements to the logic would need to be done in `@jupyterlab/lsp` package.
