### ISSUE TITLE
Compatibility with Multiple Completer Extensions

### ISSUE THREAD

**Issue by edzkite** [jupyter-lsp/jupyterlab-lsp#236]
## Elevator Pitch
Kite is planning on creating an extension for JupyterLab, as a fork of this extension. Ideally, if users have both this extension and Kite's extension installed, things should just work.

## Motivation
Based off my understanding of JupyterLab's `completer-extension` [package](https://github.com/jupyterlab/jupyterlab/blob/master/packages/completer-extension/src/index.ts) and JupyterLab-LSP's implementation, it's only possible to have one connector per notebook or file.

Creating this issue to understand if:
1. That assessment is accurate
2. If so, what it'd take to support multiple connectors, e.g. LSPConnector + KiteLSPConnector across extensions
3. Alternates to achieve said goal.

**Comment by bollwyvl** [comment]
> fork of this extension. 

I for one am happy to find ways to add more composite behavior to this repo: we're just two maintainers and a handful of contributors, and we're still hustling to make what we have work predictably. On #76, we've laid out (and have slowly been moving towards) a repo structure and workflow to allow for this, and #184 points towards supporting more kinds of sources. I also certainly feel kernels themselves need to get in the game, and be able to interact with (or act in place of) language servers. 

> it's only possible to have one connector per notebook or file.

When these show up, it usually indicates a need to:
- carve out the functionality into something standalone (as an extension)
- make it look as much like core lab as possible
- propose it to lab core, ideally in a non-breaking way
- get it merged and released
- deprecate the standalone extension

So someplace, there needs to be a `MultiCompletionConnector` to which multiple completion sources get registered... a bit tired to dig further, but it seems like getting a `composite` added somewhere in the [`CompletionManager`](https://github.com/jupyterlab/jupyterlab/blob/7fb018558f9c812e3e2a3355fb6ab7c1a30486d8/packages/completer/src/tokens.ts#L18) spec would make the most sense, followed by some additions to the [extension](https://github.com/jupyterlab/jupyterlab/blob/7fb018558f9c812e3e2a3355fb6ab7c1a30486d8/packages/completer-extension/src/index.ts#L89). Then some kind of connector voodoo, and some rules around how quickly they come back: i'd wager if we get client-side stuff in, it's going to come back _real fast_, and it would be a shame to wait for a websocket roundtrip to a server process (or third party call) to slow _all_ of that down. So maybe there's a model missing, too.

**Comment by krassowski** [comment]
This now works in JupyterLab 4.0 with jupyterlab-lsp 5.0 since we use completion provider API.
