### ISSUE TITLE
Support/test a Robot Framework language server

### ISSUE THREAD

**Issue by bollwyvl** [jupyter-lsp/jupyterlab-lsp#332]
## Elevator Pitch

Adding support for autodetecting a robot framework language server

## Motivation

- [robotframework-lsp](https://pypi.org/project/robotframework-lsp) has shipped a couple solid versions, and has a product built around it
  - the [conda-forge](https://github.com/conda-forge/staged-recipes/pull/12548) process has been started
- we have lots of examples, and this would increase our ability to dogfood diverse languages in building this code

## Design Ideas

- add to environment
- add spec
- add tests, etc.
- add robotframemework [syntax mode](https://github.com/robots-from-jupyter/robotkernel/tree/master/src/jupyterlab_robotmode)
  - it's part of `robotkernel`, which we _could_ choose to add to the development environment
  - i'm pretty much the original author of that syntax mode, and owe an update for some of the new syntax  (some for loop stuff isn't handled correctly), but it basically works, today

**Comment by krassowski** [comment]
Is the syntax mode effectively a mimetype extension?

**Comment by bollwyvl** [comment]
Yeah.... It uses code mirror "simple" mode, so could actually be encoded as
json... except I think I use some freaky regex flags... Haven't looked in a
while.

Side note: testing cm modes is _brutal_... There's whether it looks right
when you're done typing... And not hanging the browser while you're in the
middle of it. My original testing approach was pretty intense... Do
screenshots of every example from the user guide, get those right
(visually) then go back and do them keystroke by keystroke. Gaaaahhhh

**Comment by bollwyvl** [comment]
Is up on conda-forge: https://anaconda.org/conda-forge/robotframework-lsp

**Comment by bollwyvl** [comment]
Of note (and also now up on conda-forge): https://github.com/jupyter-xeus/xeus-robot

This kernel (which depends on the robotframework-lsp, now with a couple released versions) supports the debugger integration.

I'll probably take a crack at this, as some of the other stuff in-flight is still a bit blocked...
