### ISSUE TITLE
CamelCase naming convention?

### ISSUE THREAD

**Issue by qzchenwl** [jupyter-lsp/jupyterlab-lsp#47]
I see codes like:

```typescript
  connect_completion() {
    // see https://github.com/jupyterlab/jupyterlab/blob/c0e9eb94668832d1208ad3b00a9791ef181eca4c/packages/completer-extension/src/index.ts#L198-L213
    const cell = this.widget.content.activeCell;
    this.set_completion_connector(cell);
    const handler = this.completion_manager.register({
      connector: this.current_completion_connector,
      editor: cell.editor,
      parent: this.widget
    });
    this.widget.content.activeCellChanged.connect((notebook, cell) => {
      this.set_completion_connector(cell);

      handler.editor = cell.editor;
      handler.connector = this.current_completion_connector;
    });
  }
```

The JupyterLab project's naming convention is CamelCase, eg.`this.widget.content.activeCellChanged`, it looks better if the extension code use the same naming convention.

**Comment by krassowski** [comment]
Yes, it is planned, but this is low priority. I find the snake case easier to read and therefore used it for the extension at the prototyping phase; moreover, it allowed me to easily distinguish the code from the extension itself and classes extended by inheritance. As we are mostly past prototyping phase and most of the code is no longer inheriting from our dependencies I welcome the change, but I will postpone it to reduce merge conflicts.
