### ISSUE TITLE
Why is the diagnostics underline so weird

### ISSUE THREAD

**Issue by memeplex** [jupyter-lsp/jupyterlab-lsp#615]
## Description

You can even see that in the screenshot in your README:

![image](https://user-images.githubusercontent.com/2845433/120433184-4efe7b80-c351-11eb-8fc5-e55f35ba1b4b.png)

The dashes are irregular, of noticeable different sizes. I've seen many examples worse than that.

## Reproduce

Just force some diagnostic, specially one with a long underline.

## Expected behavior

Regular underline, with equal size dashes or whatever.

## Context

- Operating System and version: MacOS Big Sur.
- Browser and version: Chrome 91
- JupyterLab version: 3.0.16

<details><summary>Required: installed server extensions</summary>
<pre>
Paste the output from running `jupyter server extension list` (JupyterLab >= 3)
or `jupyter serverextension list` (JupyterLab < 3) from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
Paste the output from running `jupyter labextension list` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
Paste the output from your browser JavaScript console replacing the text in here.

To learn how to open the developer tools in your browser:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser
If too many messages accumulated after many hours of working in JupyterLab,
consider refreshing the window and then reproducing the bug to reduce the noise in the logs.

</pre>
</details>

**Comment by krassowski** [comment]
Why: because Chrome renders it as such. This looks more consistent in Firefox:

![Screenshot from 2021-06-02 11-45-02](https://user-images.githubusercontent.com/5832902/120467338-fe5e4100-c397-11eb-9583-958060035808.png)

Ideally I would want to have wavy underline instead, but there is this even more annoying bug in Chrome which means that it would not be shown for characters with width less that width of one wavelet (https://bugs.chromium.org/p/chromium/issues/detail?id=668042#c5, https://stackoverflow.com/questions/57559588).

The alternative would be to use background-image or to adjust the CSS styling of the underlines. Your proposals/contributions are very welcome to improve this.

**Comment by krassowski** [comment]
The relevant CSS code is in:

https://github.com/krassowski/jupyterlab-lsp/blob/master/packages/jupyterlab-lsp/style/highlight.css

and the variables are in:

https://github.com/krassowski/jupyterlab-lsp/blob/master/packages/jupyterlab-lsp/style/variables/base.css

**Comment by bollwyvl** [comment]
another extremely heavyweight "solution" would be [codemirror line widgets](https://codemirror.net/demo/widget.html) though I am not sure if they can be typographically sound enough to imitate underlines (considering line wrap, fancy code effects like gfm, etc).

**Comment by NoobMaster1999** [comment]
Can I solve the issue??

**Comment by krassowski** [comment]
Feel welcome to give it a try!

**Comment by krassowski** [comment]
Closing as jupyterlab-lsp 5.0 (currently in beta) uses squiggly underlines instead.
