### ISSUE TITLE
Do we need to do anything special to export licences for JupyterLab UI?

### ISSUE THREAD

**Issue by krassowski** [jupyter-lsp/jupyterlab-lsp#622]
The awesome table/list of licenses introduced upstream in JupyterLab 3.1 (https://github.com/jupyterlab/jupyterlab/pull/9519 and https://github.com/jupyterlab/jupyterlab/pull/9779) shows the extension but for now it is empty. I have not explored this topic yet so I do not know if any action is needed on part of extensions, but wanted to open this here to remember about it later on.

![Screenshot from 2021-06-11 20-51-09](https://user-images.githubusercontent.com/5832902/121742721-249e8200-caf8-11eb-8dd3-68c2d8e547ab.png)

**Comment by bollwyvl** [comment]
Theoretically, one would just need to bump ***@***.***/builder` to the
latest alpha, and it will generate the default third-party-licenses.json
which gets picked up server and finally requested by lab.

But we might change that well-known file format again, if we can make it
Other People's Schema (e.g. spdx.json), so I wouldn't worry about it too
much until  there's a real 3.1 release.

**Comment by krassowski** [comment]
Works as of jupyterlab-lsp 5.0 beta1 (and probably much earlier):

![Screenshot from 2023-09-04 01-14-35](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/5832902/d544cac1-7741-4da1-bf97-f60d2e597f1c)
