### ISSUE TITLE
autocompletion suggest from IRKernel disappeared after r languageserver enabled

### ISSUE THREAD

**Issue by TTTPOB** [jupyter-lsp/jupyterlab-lsp#639]
## Description

autocompletion suggest from IRKernel disappeared after r languageserver enabled
I cant show a thing which is disappeared so...
but I will try
If I turn off LSP autocompletion with
`"disableCompletionsFrom": ["LSP"]`

![image](https://user-images.githubusercontent.com/19909103/124764123-380e0300-df67-11eb-9470-952c3b67e4c5.png)
no matter how hard I hit `TAB` I won't get any autocompletion suggest.
But in python kernel, 
![image](https://user-images.githubusercontent.com/19909103/124764440-87ecca00-df67-11eb-9854-b4c53baf2799.png)

## Reproduce

1. Create an R notebook
2. Trigger a completion
3. You won't see completion suggests from IRKernel

## Expected behavior

See completion suggests from IRKernel

## Context

- Operating System and version: CentOS Linux 7 (Core) x86_64
- Browser and version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.64`
- JupyterLab version: `3.0.16`

<details><summary>Required: installed server extensions</summary>
<pre>
Config dir: /NAS392047/home/xxx/.jupyter

/home/xxx/anaconda/lib/python3.8/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
Config dir: /home/xxx/anaconda/etc/jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 1.4.0 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.0.16 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK

Config dir: /usr/local/etc/jupyter
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
▶ jupyter labextension list
JupyterLab v3.0.16
/home/xxx/anaconda/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
        @krassowski/jupyterlab-lsp v3.8.0 enabled OK (python, jupyterlab-lsp)

Other labextensions (built into JupyterLab)
   app dir: /NAS392047/home/xxx/anaconda/share/jupyter/lab
        @axlair/jupyterlab_vim v0.13.4 enabled OK
        @lckr/jupyterlab_variableinspector v3.0.9 enabled OK

Uninstalled core extensions:
    @karosc/jupyterlab_dracula
    @ryantam626/jupyterlab_code_formatter

</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
Paste the output from your browser JavaScript console replacing the text in here.

To learn how to open the developer tools in your browser:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser
If too many messages accumulated after many hours of working in JupyterLab,
consider refreshing the window and then reproducing the bug to reduce the noise in the logs.

</pre>
</details>

**Comment by krassowski** [comment]
You are right, it seems that we are not asking R kernel for completions. From a quick look it seems that this is because one of a difference between `R` and `r` in:

https://github.com/krassowski/jupyterlab-lsp/blob/e85d73f6577f586dfdc5080f12c420e4d3079b12/packages/jupyterlab-lsp/src/features/completion/completion_handler.ts#L263-L265

In addition there might be a problem with `this.trigger_kind` in:

https://github.com/krassowski/jupyterlab-lsp/blob/e85d73f6577f586dfdc5080f12c420e4d3079b12/packages/jupyterlab-lsp/src/features/completion/completion_handler.ts#L194-L204

I will investigate soon.

**Comment by TTTPOB** [comment]
I have no experience for ts/js, but I am happy to test a dev version

**Comment by TTTPOB** [comment]
sorry for the spam but is there any update on this issue?

**Comment by TTTPOB** [comment]
FYI
I recently started to use vscode to do my daily job on jupyter
running r language server on it also cause IR kernel completion disappear, but on python jupyter notebook it's ok

**Comment by TTTPOB** [comment]
thank you!
