### ISSUE TITLE
Path completion broken

### ISSUE THREAD

**Issue by michaelaye** [jupyter-lsp/jupyterlab-lsp#667]
After installing jlab-lsp, path completion is broken for me.

I verified that after removing jlab-lsp it works again.

What happens is that the first letters already typed before triggering the completion are not being removed by the replacement, which results in having to edit the completed path, rendering it unusable.

Below are 2 screenshots showing what I typed just before and just after accepting the completion suggestion:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/69774/130007996-98bde30b-9b2d-40f7-ba82-0a66cc596fa8.png">

<img width="237" alt="image" src="https://user-images.githubusercontent.com/69774/130008018-6569ad2d-69a9-4e8e-9bab-b12429999746.png">

Versions:
```bash
# Name                    Version                   Build  Channel
jupyter                   1.0.0            py39h6e9494a_6    conda-forge
jupyter-lsp               1.4.1              pyhd8ed1ab_0    conda-forge
jupyter-server-mathjax    0.2.3              pyhd8ed1ab_0    conda-forge
jupyter-server-proxy      3.1.0              pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_core              4.7.1            py39h6e9494a_0    conda-forge
jupyter_nbextensions_configurator 0.4.1            py39h6e9494a_2    conda-forge
jupyter_server            1.10.2             pyhd8ed1ab_0    conda-forge
jupyterlab                3.1.7              pyhd8ed1ab_0    conda-forge
jupyterlab-git            0.32.1             pyhd8ed1ab_0    conda-forge
jupyterlab-lsp            3.8.1              pyhd8ed1ab_0    conda-forge
jupyterlab_code_formatter 1.4.10             pyhd8ed1ab_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.7.1              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
```

**Comment by krassowski** [comment]
Thanks! I think this is because of the `~/` prefix... If the server returned the path with the prefix it should work well. We could either make it a special case if we knew that it is a path completion (but we don't since the server did not mark it as a File but as a Text) or we could fix it in the pyls language server.

**Comment by michaelaye** [comment]
I confirmed that things work without the tilde.
Maybe this should work the same as without the server, where standard completion would be that the tilde is replaced at the first completion action (Path().expanduser() in case you use pathlib tools), and afterwards there's only an absolute path left.

**Comment by michaelaye** [comment]
ah no, absolute paths also fail:

<img width="230" alt="image" src="https://user-images.githubusercontent.com/69774/130114761-1c42a77c-08d4-4919-bfee-d8ed57f85d43.png">

**Comment by michaelaye** [comment]
Can one switch off path completion by `lsp` only?

**Comment by krassowski** [comment]
I'm sorry I did not resolve it yet. I will look into it as soon as possible for me, which is the weekend 9-10 October. I added it to my calendar. Sorry again!

**Comment by krassowski** [comment]
You can add `"disableCompletionsFrom": ["LSP"]` in `Advanced Settings Editor` → `Code Completion`. I confirmed that this fixes the problem and it is only present for specific prefixes when merging completions from Kernel and LSP; sorry - these are using different coordinate systems and it's just hard to reconcile them in all edge cases. Working on it!
