### ISSUE TITLE
Set Up Problems

### ISSUE THREAD

**Issue by hayashady** [jupyter-lsp/jupyterlab-lsp#706]
Hello,

I am trying to set up jupyerlab-lsp on my machine.

I have downloaded jupyerlab-lsp, but it is not active inside jupyterlab notebook. 

My auto complete still looks like this:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/85594498/142482546-ea92d73f-d44f-43e6-a074-b50ce005b884.png">

How do I turn jupyerlab-lsp on?

**Comment by hayashady** [comment]
Sorry, perhaps this is working. What I am looking for is the panel on the right that includes documentation information about classes (say, pd.dataframe), as well as the panel above the code that includes the parameters for whatever I am doing. For instance, when typing parameters of a data frame, a window is shown above where I am coding that shows parameters and defaults.

**Comment by krassowski** [comment]
Have you installed a language server? Could you fill in [bug report template](https://github.com/jupyter-lsp/jupyterlab-lsp/issues/new?assignees=&labels=&template=bug_report.md), please?

**Comment by krassowski** [comment]
Hi, I will close this one as we did not hear back from you in the last three weeks. I hope you managed to configure the extension and set up the language server of your choice; if this is not the case, please reopen providing the details which will allow us to help you.

In case of any further questions or suggestions you are welcome to open a new issue.
