### ISSUE TITLE
Sorting by Line:Ch in Diagnostics Panel does not work

### ISSUE THREAD

**Issue by StefanBrand** [jupyter-lsp/jupyterlab-lsp#707]
## Description
I tried to sort by "Line:Ch" because I was mainly interested in the class that I had added to the module. Turns out that this functionality is broken.

![image](https://user-images.githubusercontent.com/8948865/142989925-aa46761a-ccd1-44c6-963e-0a14235564e7.png)

## Reproduce

1. Produce some errors
2. Try to sort by "Line:Ch" in Diagnostics Panel

## Expected behavior

Diagnostics Panels is sorted by "Line" first, then by "Ch".

## Context

- Operating System and version: Ubuntu 20.04
- Browser and version: 94.0
- JupyterLab version: 3.1.8

<details><summary>Required: installed server extensions</summary>
<pre>
Config dir: /home/jovyan/.jupyter

'CATALOG_NAME'
/opt/conda/lib/python3.9/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
Config dir: /opt/conda/etc/jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 1.5.0 OK
    jupyter_server_mathjax enabled
    - Validating jupyter_server_mathjax...
      jupyter_server_mathjax  OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.1.8 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic  OK
    nbdime enabled
    - Validating nbdime...
      nbdime 3.1.0 OK

Config dir: /usr/local/etc/jupyter
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v3.1.8
/opt/conda/envs/agri_data-0.87/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

/home/jovyan/.local/share/jupyter/labextensions
        @voila-dashboards/jupyterlab-preview v2.0.1 enabled OK (python, voila)

/opt/conda/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.0 enabled OK
        jupyterlab_filetree v0.2.1 enabled OK (python, jupyterlab_filetree)
        edc-jlab v0.5.10 enabled OK (python, edc_jlab)
        jupyterlab-drawio v0.9.0 enabled OK (python, jupyterlab-drawio)
        @krassowski/jupyterlab-lsp v3.9.1 enabled OK (python, jupyterlab-lsp)
        @lckr/jupyterlab_variableinspector v3.0.9 enabled OK (python, lckr_jupyterlab_variableinspector)
        @ryantam626/jupyterlab_sublime v0.4.1 enabled OK (python, jupyterlab_sublime)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab

Disabled extensions:
    @jupyterlab/filebrowser-extension:download
    @jupyterlab/filebrowser-extension:share-file
</pre>
</details>

**Comment by krassowski** [comment]
Thank you. Looks like the code for sorting is wrong. The relavant code is here:

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/0cff6b9cd7dab4d44f877cf7bacc91bf72c6ec4e/packages/jupyterlab-lsp/src/features/diagnostics/listing.tsx#L224-L252
