### ISSUE TITLE
Configuration details to use multiple language servers (pyright and python-lsp-server)

### ISSUE THREAD

**Issue by sntgluca** [jupyter-lsp/jupyterlab-lsp#708]
## What I am trying to do...
Hi!

In my current experience, Pyright seems to outperform Jedi (and python-lsp-server) when using autocomplete.

Based on the work in #587, I would like to be able to configure Pyright as the main language server, but keep running python-lsp-server as a linter.

I tried the suggestions in #587, the secondary language server is "available" but it doesn't run.

May you share configuration insights to run the two servers together?

I keep thinking this project if of outmost importance for the Jupyter community, to let Jupyter compete with most mature IDEs... thanks for the continuous improvements!

**Comment by nyngwang** [comment]
@sntgluca Did you solve it/

**Comment by sntgluca** [comment]
Hi, I am sorry I didn't reply earlier. Completely missed it.

I could not make any progress. I am not sure if this is a supported feature now...

**Comment by krassowski** [comment]
Thank you for the interest, PRs are welcome! Closing as a duplicate of https://github.com/jupyter-lsp/jupyterlab-lsp/issues/437.
