### ISSUE TITLE
jupyterlab-lsp and Jupyterhub - not initializing...

### ISSUE THREAD

**Issue by cablesky** [jupyter-lsp/jupyterlab-lsp#709]
If I run jupyterlab-lsp in a local Docker container, it works without any problems.
However, if the same Docker image is running in Jupyerhub, the initialization no longer works. The message "Initializing..." appears permanently.
My Dockerfile is:

> FROM jupyter/minimal-notebook:latest
> RUN conda install -c conda-forge python=3
> RUN conda install -c conda-forge jupyterlab-lsp
> RUN conda install -c conda-forge python-lsp-server r-languageserver

What can i do?

**Comment by krassowski** [comment]
Duplicated of #674. Please fill in the [bug issue template](https://github.com/jupyter-lsp/jupyterlab-lsp/issues/new?assignees=&labels=&template=bug_report.md) and add it as a commend in #674. In principle there should not be a reason for it to not work (it works perfectly on binder) other than something in configuration that may need to be needed to unblock connections. This needs investigation from someone who experiences the problem. I can recommend what to check once you add the filled in template there.
