### ISSUE TITLE
Log level for jupyterlab-lsp <-> pygls setting?

### ISSUE THREAD

**Issue by asteppke** [jupyter-lsp/jupyterlab-lsp#715]
With the jupyterlab-lsp (3.9.1) on Jupyterlab (3.2.4, Windows) activated my console is flooded with messages from the `pygls` module: 

````
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 0, "result": {"capabilities": {"textDocumentSync": {"openClose": true, "change": 2, "willSave": false, "willSaveWaitUntil": false, "save": true}, "completionProvider": {"triggerCharacters": [".", "'", "\""], "resolveProvider": true}, "hoverProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ","]}, "definitionProvider": true, "referencesProvider": true, "documentHighlightProvider": true, "documentSymbolProvider": true, "codeActionProvider": {"codeActionKinds": ["refactor.inline", "refactor.extract"]}, "renameProvider": true, "executeCommandProvider": {"commands": []}, "workspaceSymbolProvider": true, "workspace": {"workspaceFolders": {"supported": true, "changeNotifications": true}, "fileOperations": {}}}}}
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 1, "result": null}
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 2, "result": null}
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 3, "result": null}
INFO:pygls.protocol:Sending data: {"jsonrpc": "2.0", "id": 4, "result": null}
[...]
````

As far as I can see with the current settings of the juypterlab-lsp the log level should be much stricter:

````
    // Log all LSP communication with the LSP servers
    // Whether all messages sent to and received from LSP servers should be logged into the console. To see these messages, set loggingLevel to debug or log. Note: Only messages handled by the new API will be shown.
    "logAllCommunication": false,

    // Logging console type
    // The console to use for debugging problems with this extension. Allowed values are: browser, floating.
    "loggingConsole": "browser",

    // Logging console verbosity level
    // The verbosity of the console for debugging problems with this extension. Allowed values are: debug, log, warn, error.
    "loggingLevel": "warn",
````

Is there a separate setting to suppress this flood of messages? Otherwise the console becomes unusable.

**Comment by krassowski** [comment]
Which console do you mean? The one in the browser or the terminal where you start JupyterLab from? What language server are you using? This might not be a problem on our part but something with pygls setting.

**Comment by selasley** [comment]
I see the same thing.  The terminal used to start JupyterLab is constantly getting INFO:pygls messages

python 3.10.1 from python.org running under macOS 11.6.2
some items from pip3 list:

    ipython                   7.30.1
    ipython-genutils          0.2.0
    jupyter-client            7.1.0
    jupyter-core              4.9.1
    jupyter-lsp               1.5.1
    jupyter-server            1.13.1
    jupyterlab                3.2.5
    jupyterlab-code-formatter 1.4.10
    jupyterlab-lsp            3.9.2
    jupyterlab-pygments       0.1.2
    jupyterlab-server         2.9.0
    pygls                     0.11.3
    python-lsp-jsonrpc        1.0.0
    python-lsp-server         1.3.3

Thanks for any help you can provide.

**Comment by krassowski** [comment]
Do you have jedi language server installed?

**Comment by selasley** [comment]
Yes

        jedi                      0.18.1
        jedi-language-server      0.34.12

**Comment by krassowski** [comment]
I believe it is coming from jedi language server. It's weird because we're do not enable the verbose flag. Could you open an issue on https://github.com/pappasam/jedi-language-server please?

**Comment by selasley** [comment]
[https://github.com/pappasam/jedi-language-server/issues/186#issue-1079266541](https://github.com/pappasam/jedi-language-server/issues/186#issue-1079266541)

**Comment by krassowski** [comment]
Closing, as the verbosity setting was improved upstream in https://github.com/pappasam/jedi-language-server/pull/188 and new version of jedi-language-server is now available. If you are seeing this problem please upgrade `jedi-language-server` to v0.35.0 or newer.
