### ISSUE TITLE
Improve visibility of under-described diagnostics

### ISSUE THREAD

**Issue by bollwyvl** [jupyter-lsp/jupyterlab-lsp#743]
## Elevator Pitch

Allow expanding zero-sized diagnostics so they are visible with in-line editor marks (e.g. squiggle underlines).

## Motivation

Some servers (or there linters), such as those added in #724, provide diagnostics in-editor that we don't display because they have zero size. We can still see them in the diagnostic panel.

While expanding them to at least one character would make them somewhat visible, it may be preferrable for them to be even bigger, either the rest of the line or the entire line. 

## Design Ideas

Add a setting, `expandZeroWidthDiagnostics: int`. The default value could be `1`, while, ideally, a `-1` would expand to the end of the line.

## Alternatives

CodeMirror 5 offers some other marks including:
- gutters (like line numbers and breakpoints)
  - at present these are kind of perilous as debugger/lineNumbers are managed rather coarsely
- line widgets
  - thes put entire lines above/below the line in question

These could be explored as well, and might be preferable for other users and use cases.

**Comment by krassowski** [comment]
Closing, as in jupyterlab-lsp 5.0 there is a dedicated triangle indicator for zero-sized diagnostics now thanks to CodeMirror 6 linter.
