### ISSUE TITLE
How to disable Diagnostics yellow underlining?

### ISSUE THREAD

**Issue by kwon14** [jupyter-lsp/jupyterlab-lsp#751]
Hello. Thank you always for your great work.
I am wondering if there is a way to make only the red underline appear.

Whether there is a separate option in code Diagnostics,
Ask if other options are available.
(I hope there is no yellow underline. Make sure that only the red underline for errors appears.)

thank you.

**Comment by krassowski** [comment]
Thanks for opening this one. This is an interesting proposal. I don't believe it is currently possible, but we could have an extra setting called `ignoreSeverities` to complement existing `ignoreCodes` and `ignoreMessagesPatterns`.

**Comment by drscotthawley** [comment]
@krassowski   Just another vote for this.  Seeing so much yellow underling makes it hard to read my text. 
![Screen Shot 2023-05-24 at 1 34 28 PM](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/13925685/89914dfe-67fd-4e9c-9b15-bfb0bb4085cb)

I've searched the View and Settings menu for some way to turn this off and have found nothing. 

It would be helpful to have button or View option to immediately turn this off.   Would prefer not to be forced to hunt through some detailed Settings sub-menus or edit some JSON file.  Just a "[Something something] underline" toggle option in View or Settings menus.

**Comment by krassowski** [comment]
Would you like to contribute a pull request? As a workaround a faster route from UI may be right click → show diagnostics panel → right click on listing → ignore diagnostics like this → ignore diagnostics with code "X"
