### ISSUE TITLE
Jupyterlab debugger unexpected behaviour(with breakpoints on i'm not able to step into the function

### ISSUE THREAD

**Issue by hiroto01** [jupyter-lsp/jupyterlab-lsp#786]
Hi there,
my machine: MacBook Pro, 
chip: Apple M1 Pro

its been a week since im using jupyter lab. It worked well at first like howi use command-> 

```
conda create -n jupyterlab-debugger -c conda-forge jupyterlab=3 "ipykernel>=6" xeus-python
conda activate jupyterlab-debugger
```
to enable the jupyter debugger
kernel that im using: Pyhton3 (ipykernel)

i cloned detectron2 repository
and my aim was to see how the code flows through I'm working on instance segmentation
```

for d in random.sample(dataset_dicts, 1):
    print(d)
    img = cv2.imread(d['file_name']+'.png', cv2.IMREAD_UNCHANGED)
    if img.shape[2] == 4:     # we have an alpha channel
          # print("alpha channel")
          a1 = ~img[:,:,3]        # extract and invert that alpha
          img = cv2.add(cv2.merge([a1,a1,a1,a1]), img)   # add up values (with clipping)
          img = cv2.cvtColor(img, cv2.COLOR_RGBA2RGB)
    plt.imshow(img[:, :, ::-1])
    plt.show()
    visualizer = Visualizer(img, metadata=stroke_metadata, scale=1.0)
    # print(d)
    **out = visualizer.draw_dataset_dict(d)**
    # print(out)
    plt.imshow(cv2.cvtColor(out.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))
    plt.show()
```

the code in bold is where i had my breakpoint, when i first used debugger it worked well, the source panel took me to the detectrons code and showed the code flow in that visualizer.py file, but it doesnt now!!

this is truly bothersome and i need help ...plz look into it if it is some kind of bug?
any help would truly be appreciated!!

**Comment by hiroto01** [comment]
@krassowski plz help!

**Comment by krassowski** [comment]
I think that you might have wanted to open this issue in https://github.com/jupyterlab/jupyterlab as it does not seem to relate to jupyterlab-lsp extension ;) When you will be filling it in the correct repository, please include some screenshots and minimal reproducible example.
