### ISSUE TITLE
code completion missing string for very long path completion

### ISSUE THREAD

**Issue by niuniudevp** [jupyter-lsp/jupyterlab-lsp#787]
**Description**
When I try to type in  a file path, if the path is vey long, the remaining path string will not be seen in code completion! 
![image](https://user-images.githubusercontent.com/46774078/162099380-766265c3-451f-4631-8bb7-e2b4027a2073.png)

**Comment by dhirschfeld** [comment]
For paths, truncating the *start* of the string would likely be a much better UX.

Might even be a better UX for *everything* :thinking:

**Comment by Keppl** [comment]
Hmm, though it does cause an inverse of the issue if functions have a lot of arguments, and arguments are displayed. Not an issue with completions that don't display arguments though.
![image](https://user-images.githubusercontent.com/8963514/168124266-3b4d656c-b23d-488d-8b19-c7d08f860c09.png)

**Comment by krassowski** [comment]
We could do that conditionally on the type of completion (if it is a path then `direction: rtl;` otherwise as it was). That would however require teaching kernel to send proper types for paths (https://github.com/ipython/ipython/issues/12820).
