### ISSUE TITLE
Signature suggestion highlight color is unreadable in dark mode

### ISSUE THREAD

**Issue by plunkgj** [jupyter-lsp/jupyterlab-lsp#792]
## Description

Signature suggestion highlight color is unreadable in dark mode. It is a bright yellow which makes the white text completely unreadable. Reporting this as a bug b/c text becomes completely unreadable (probably not a bug if its just hard to read)

![Screen Shot 2022-04-15 at 11 54 37 AM](https://user-images.githubusercontent.com/17993489/163622448-50a0d6d5-232c-4dc0-8cef-22af67c36561.png)

## Reproduce

1. Activate dark mode.
2. Activate signature suggestion using any function.
3. Behold the yellow highlight for current argument.

## Context

- Operating System and version: Amazon Linux 2 (SageMaker machine)
- Browser and version:  current Chrome 4/15/22 - v100.0.4896.88 
- JupyterLab version: 3.3.2
- Language server and version: 
-- jupyterlab-lsp 3.10.1
-- python-lsp-server 1.4.1

<details><summary>Required: installed server extensions</summary>
<pre>
      jupyter_lsp 1.5.1 OK
      jupyter_server_proxy  OK
      jupyter_resource_usage 0.6.1 OK
      jupyter_server_mathjax  OK
      jupyterlab 3.3.2 OK
      jupyterlab_git 0.36.0 OK
      nbclassic  OK
      nbdime 3.1.1 OK
      notebook_shim  OK
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
        jupyterlab-plotly v5.6.0 enabled OK
        jupyterlab-stickyland v0.2.0 enabled OK (python, jupyterlab_stickyland)
        jupyterlab-execute-time v2.1.0 enabled OK (python, jupyterlab_execute_time)
        nbdime-jupyterlab v2.1.1 enabled OK
        jupyter-matplotlib v0.11.0 enabled OK
        jupyterlab-unfold v0.2.2 enabled OK (python, jupyterlab-unfold)
        jupyterlab-topbar-extension v0.6.1 enabled OK (python, jupyterlab-topbar)
        jupyterlab-simpledark v1.0.0 enabled OK (python, jupyterlab-simpledark)
        jupyterlab-system-monitor v0.8.0 enabled OK (python, jupyterlab-system-monitor)
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)
        @jupyterlab/server-proxy v3.2.1 enabled OK
        @jupyterlab/git v0.36.0 enabled OK (python, jupyterlab-git)
        @jupyter-server/resource-usage v0.6.1 enabled OK (python, jupyter-resource-usage)
        @bokeh/jupyter_bokeh v3.0.4 enabled OK (python, jupyter_bokeh)
        @krassowski/jupyterlab-lsp v3.10.1 enabled OK (python, jupyterlab-lsp)
        @dunovank/jupyterlab_legos_ui v0.2.2 enabled OK (python, jupyterlab_legos_ui)
        @dunovank/jupyterlab_darkside_ui v0.2.3 enabled OK (python, jupyterlab_darkside_ui)
</pre>
</details>

**Comment by krassowski** [comment]
This can be addressed by adding a CSS style for the `<mark>` tag using a selector like `body[data-jp-theme-light='false'] .lsp-signature-help mark` to https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/packages/jupyterlab-lsp/style/signature.css - contributions welcome.
