### ISSUE TITLE
jyputerlab-lsp not working 

### ISSUE THREAD

**Issue by Trid-collab** [jupyter-lsp/jupyterlab-lsp#793]
I have installed jupyterlab-lsp and python language server in Anaconda python 3.8, but I am not able to get the auto completions as expected. It am also not able to the 'Code Completion' option in my settings to configure the continuoushinting as mentioned in the site README. 

I have also tried installing the jupyterlab- lsp with the new experimental python language server `pip install git+https://github.com/krassowski/python-language-server.git@main` with out any success. 

Lastly I have tried installing the same with `jupyter-lsp-python` without any success. 

Do I need do any additional configuration

**Comment by Trid-collab** [comment]
Its was an installation issue . hence closing

**Comment by The1iAmNeo** [comment]
> 

can you please explain how you did the new install because i have the same issues ... i don't have the code completion option

**Comment by The1iAmNeo** [comment]
> Its was an installation issue . hence closing


can you please explain how you did the new install because i have the same issues ... i don't have the code completion option

**Comment by FlorisCalkoen** [comment]
@QuantFreedom1022, same here. Did you manage to resolve it>?

**Comment by QuantFreedom1022** [comment]
@FlorisCalkoen i just use juypter in vscode now ... so much better
