### ISSUE TITLE
Experimental python server is slow and signature not showing

### ISSUE THREAD

**Issue by Trid-collab** [jupyter-lsp/jupyterlab-lsp#794]
Have installed the experimental server `pip install git+https://github.com/krassowski/python-language-server.git@main` , but found it to slower than the community `python-lsp-server`. Also signatures are not showing up or are very very late ,slow.

Could you please help me on how to uninstall this language server as I am unable to uninstall it

**Comment by krassowski** [comment]
`pip uninstall python-language-server` should do the job. Closing, since we no longer recommend the experimental server (sorry, no time to maintain it).
