### ISSUE TITLE
pylsp - Pylint and Black

### ISSUE THREAD

**Issue by beatslikeahelix** [jupyter-lsp/jupyterlab-lsp#818]
I've successfully set up all the functionality displayed in the README, and have `flake8` working. However, I cannot get `pylint` or `black` to work, despite both being supported by pylsp (`black` needs the plugin package `python-lsp-black`, which I have) and installed in my environment. 

Over at the pylsp page, people appear to have both of these working, which makes me think it's a JupyterLab issue.
Has anyone got Pylint and Black working in JupyterLab?

Here's my config:

```json

{
    "language_servers": {
        "pylsp": {
            "serverSettings": {
                "pylsp.plugins.pycodestyle.enabled": false,
                "pylsp.plugins.mccabe.enabled": false,
                "pylsp.plugins.pyflakes.enabled": false,
                "pylsp.plugins.pydocstyle.enabled": true,
                "pylsp.plugins.flake8.enabled": false,
                "pylsp.plugins.pylint.enabled": true,
                "pylsp.plugins.black.enabled": true,
                
            }
        }
    }
}
```

Any help would be much appreciated.

**Comment by krassowski** [comment]
There is no support for black formatting currently, see #632, #373. If you have a specific issue with pylint diagnostics please provide a reproducible example, but it is highly likely that if other diagnostics providers from pylsp (pyflakes, flake8, etc) work and pylint does not, it is not an issue with jupyterlab-lsp (though I am not aware of any issues with pylsp with that respect either).

**Comment by lukelbd** [comment]
@beatslikeahelix  I use the [`jupter_code_formatter` plugin](https://github.com/ryantam626/jupyterlab_code_formatter) to automatically format cells with black and isort. So that's an option if you just want automatic formatting instead of lint messages.
