### ISSUE TITLE
Spark SQL language server

### ISSUE THREAD

**Issue by cccs-jc** [jupyter-lsp/jupyterlab-lsp#824]
hey @krassowski wanted to mention that we are mostly feature complete with our jupyterlab-sql-editor extension.

https://github.com/CybercentreCanada/jupyterlab-sql-editor

Since we make heavy use of jupyterlab-lsp I thought you might be interested in finding out more about it.

We wrote Towards Data Science articles describing its use.
https://medium.com/@jean-claude.cote/jupyterlab-sql-cell-editor-e6ac865b42df
https://medium.com/@jean-claude.cote/jinja-dbt-sql-templating-in-jupyterlab-vscode-1179e818fe17

Our extension installs itself without any modifications to jupyterlab-lsp. However we would be interested in adding it to the list of language server you have in your documentation. What would be involved in doing so.

**Comment by bollwyvl** [comment]
Good stuff, glad it's working out for you.

We don't really have such a section in [docs/Language Servers.ipynb](https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs/Language%20Servers.ipynb), as we only list stuff we test (or use in the course of development), though there are a couple more floating around out there such as [graph-lsp](https://github.com/jupyrdf/graph-lsp), [json-lsp](https://pypi.org/project/json-lsp/) and [yaml-lsp](https://pypi.org/project/yaml-lsp/).

As adding more servers-under-test to this repo is rather complicated, perhaps proposing a PR of  `docs/Third Party Language Servers.md` with a similar table structure to the the existing one would be appropriate, with links in the ToC, and at the bottom of the page.

Alternately, it could be another notebook and YAML file with these columns... this might actually be a bit more consistent and easier to PR against, as collaboratively editing Markdown tables isn't much fun.

**Comment by cccs-jc** [comment]
@bollwyvl that sounds good. We'll add ourselves to the markdown file. I can't find it in the repo. Is it something generated?

**Comment by bollwyvl** [comment]
No, it would need to be added to the `docs` folder.

**Comment by krassowski** [comment]
Maybe creating a yaml file but adding the result as a section in [docs/Language Servers.ipynb](https://github.com/jupyter-lsp/jupyterlab-lsp/blob/master/docs/Language%20Servers.ipynb) instead of a new page could end up being more discoverable for users?

**Comment by cccs-jc** [comment]
I'm not too familiar with how the documentation generator works. I have placed this file which contains information for jupyterlab-sql-editor. It would be great if someone could integrate this into the documentation for me. I'm sure you guys can do this way faster than I can ;-)
https://github.com/jupyter-lsp/jupyterlab-lsp/pull/826

**Comment by krassowski** [comment]
Thank you. I pushed to your branch and will merge once checks pass.

**Comment by cccs-jc** [comment]
thanks @krassowski much appreciated

**Comment by krassowski** [comment]
Closing as addressed by #826, thanks again!
