### ISSUE TITLE
Does LSP support jupyter notebook?

### ISSUE THREAD

**Issue by km5ar** [jupyter-lsp/jupyterlab-lsp#853]
I'm trying to install LSP on jupyter notebook
However, I only saw instruction for jupyter lab, I did not see there are any instruction on how to install it on notebook.

Any suggestion?

**Comment by km5ar** [comment]
Thank you for your answer!!!!

**Comment by krassowski** [comment]
The jupyterlab-lsp 5.0 (currently in beta) supports Notebook 7. There are some things that could be improved, e.g. placing the diagnostics panel on the side. Closing as this is answered.
