### ISSUE TITLE
Automate release/integrity

### ISSUE THREAD

**Issue by bollwyvl** [jupyter-lsp/jupyterlab-lsp#88]
For https://github.com/krassowski/jupyterlab-lsp/pull/86#issuecomment-548388841

- `integrity.py` should accept a `--fix` for automateable things
  - CHANGELOG actually takes (valuable) work, though
- `release.py` should be able to perform releases (and check integrity)
  - the `README.md`s are a challenge, as there should be _something_ pretty on the npm/pypi page, but it's fairly annoying to have to make all the relative refs work
    - perhaps have the root `README.md` reference local assets, and "render" them into package folders (e.g. replace relative links with static ones)
      - or only have those files exists during `release.py`
      - or check them in, and check them with `integrity.py`
  - this can be run every time in ci, and stored as an artifact along with `SHA256SUMS`
    - with some-day publishing (though we have shied away from this on Lab for the time being)

**Comment by krassowski** [comment]
Notes to future self:
- `npm publish` from `/packages/jupyterlab-lsp`.
- `lsp-ws-package` needs a version pin
- I have a publish script to share (but release/bump version script still needs to be created)

**Comment by krassowski** [comment]
Closing in favour of [#691 Adopt the Jupyter Releaser](https://github.com/jupyter-lsp/jupyterlab-lsp/issues/691)
