### ISSUE TITLE
jupyter-lsp crash when jupyter lab start directory is in a different drive

### ISSUE THREAD

**Issue by armonyG** [jupyter-lsp/jupyterlab-lsp#886]
## Description

After installing jupyterlab-lsp and python-lsp-server none of the features completion features work, not even the kernel completion.
The LSP server is fully initialized:
![image](https://user-images.githubusercontent.com/23078645/207334099-0c39345a-940f-4f56-a8e3-a302437bf5f7.png)

The features appear in the setting and the context menu but they do not work, e.g. the rename doaloge box opens but it doesn't rename the symbol:
![image](https://user-images.githubusercontent.com/23078645/207338321-db8fbf25-c9f3-43dc-8228-b1802fdc8c6d.png)

Looking at the terminal running jupyter lab, after every action there is an traceback the ends with
`ValueError: path is on mount 'C:', start on mount '\\\\<path to network drive>\\data`
For example:
![image](https://user-images.githubusercontent.com/23078645/207347932-485bbd5d-18f5-40e2-b3df-204814acb589.png)

The network location is mapped with a drive letter on windows.

My guess is that I need to add the network drive to a jupyter path so jupyterlab-lsp can use it but i am not sure which what and where.
jupyter --path gives
![image](https://user-images.githubusercontent.com/23078645/207351462-208cdcf3-0649-44fe-b35c-100f956c9490.png)

## Reproduce

1. Open an anaconda prompt
2. Navigate to a different (network) drive
3. start jupyter lab (jupyter-lab)
4. Use any existing or new notebook

## Context
- Operating System and version: a VM with restricted internet access (conda is allowed) Windows Server 2019 Datacenter
- Browser and version: Google Chrome 89.0.4389.90
- JupyterLab version: 3.5.0
- Language server and version: 3.10.2
- python-lsp-serv version: 1.2.1

<details><summary>Required: installed server extensions</summary>
![image](https://user-images.githubusercontent.com/23078645/207344262-d4267032-ff7d-4327-9148-1fa20df08818.png)
</details>

<details><summary>Required: installed lab extensions</summary>
![image](https://user-images.githubusercontent.com/23078645/207353454-51d59bce-5112-45f4-92e7-e96892d00828.png)
</details>

<details><summary>Troubleshoot Output</summary>
Too long for screenshots (can't copy from that restricted VM)

If necessary I can export the data
</details>

<details><summary>Command Line Output</summary>
Too long for screenshots (can't copy from that restricted VM)

If necessary I can export the data
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
Too long for screenshots (can't copy from that restricted VM)

If necessary I can export the data
</details>

**Comment by armonyG** [comment]
Hello,

I tried to set so `path`  is on the same mount as `start` by setting JUPYTER_DATA_DIR environment variable to be on the network mount:
![image](https://user-images.githubusercontent.com/23078645/216293244-77980d49-e416-40fc-9e7c-9cc4844a4cb7.png)
(Z:\ is the drive letter for where jupyterlab starts)
But still I get the same `ValueError: path is on mount 'C:', start on mount '\\\\<path to network drive>\\data`
So `path` is not taken from here.

I followed the trackback and `path` is coming from `Workspace.root_uri` but I couldn't find where is this path taken from.

@krassowski is trying to set the `root_uri` to the network drive even a good idea?

**Comment by armonyG** [comment]
This issue is not resolved in version 4.0.0

**Comment by krassowski** [comment]
Thank you for the report and update. Looking at the traceback this is not an issue with jupyterlab-lsp but with [python-lsp-server](https://github.com/python-lsp/python-lsp-server) which is one of many servers you can use with jupyterlab-lsp. Would you mind opening an issue over there and linking it back please?

**Comment by armonyG** [comment]
@krassowski this is indeed related! The suggest fix does not work for me since I really have two different mounts
It did however, led me to a different solution which is not general so it is not suitable for a PR.
I will post this issue to the [python-lsp-server](https://github.com/python-lsp/python-lsp-server), with a bit more insight to what the source of the problem.
