### ISSUE TITLE
`Jump to Definition` does not jump to `.pyi` if the corresponding runtime module is a compiled extension in the same directory

### ISSUE THREAD

**Issue by bzoracler** [jupyter-lsp/jupyterlab-lsp#889]
## Description & Reproduction

For the following package arrangement,

```
📂site-packages
 ┗━📂my_package
   ┣━📜__init__.py
   ┣━📦my_compiled_python_extension_module.so
   ┗━📜my_compiled_python_extension_module.pyi
```

`Jump to Definition` cannot jump to `📜my_compiled_python_extension_module.pyi` (message: `No jump targets found`).

The jump is successful if `📦my_compiled_python_extension_module.so` doesn't exist.

## Expected behavior

`Jump to Definition` behaves as if `📦my_compiled_python_extension_module.so` doesn't exist, and successfully jumps to the `.pyi` file.

## Context

- Operating System and version: Ubuntu Studio 22.04 (LTS)
- Browser and version: Firefox 108.0.1 (64-bit) Snap for Ubuntu
- JupyterLab version: 3.4.5
- Language server and version: 3.10.1

<details><summary>Required: installed server extensions</summary>
<pre>
Paste the output from running `jupyter server extension list` (JupyterLab >= 3)
or `jupyter serverextension list` (JupyterLab < 3) from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

```shell
jupyter server extension list
```
```shell
Config dir: ~/.jupyter

Config dir: ~/pyenv/versions/3.10.5/envs/<venv>/etc/jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 1.5.1 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.4.5 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic 0.4.3 OK
    notebook_shim enabled
    - Validating notebook_shim...
      notebook_shim  OK

Config dir: /usr/local/etc/jupyter
```
<details><summary>Required: installed lab extensions</summary>
<pre>
Paste the output from running `jupyter labextension list` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

```bash
jupyter labextension list
```
```bash
JupyterLab v3.4.5
~/pyenv/versions/3.10.5/envs/<venv>/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        pyi-highlighting v0.1.0 enabled OK (python, pyi_highlighting)
        @krassowski/jupyterlab-lsp v3.10.1 enabled OK (python, jupyterlab-lsp)
        @jupyter-widgets/jupyterlab-manager v3.1.1 enabled OK (python, jupyterlab_widgets)
```

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
Paste the output from your browser JavaScript console replacing the text in here.

To learn how to open the developer tools in your browser:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser
If too many messages accumulated after many hours of working in JupyterLab,
consider refreshing the window and then reproducing the bug to reduce the noise in the logs.

</pre>
</details>

**Comment by bzoracler** [comment]
Looks like this was behaviour introduced in `pylsp` a while back. I've posted an issue there instead (https://github.com/palantir/python-language-server/issues/960).

**Comment by krassowski** [comment]
Thanks for following up and placing the issues in appropriate repositories, this helps a lot. For what is worth I agree that sub files should be supported across the board.
