### ISSUE TITLE
LaTeX chktex failing on CI on Windows (again)

### ISSUE THREAD

**Issue by krassowski** [jupyter-lsp/jupyterlab-lsp#894]
First seen on #892 and then independently on #893. #891 was still ok.

**Comment by krassowski** [comment]
This appears to be thank to texlab 5.0 release: https://github.com/latex-lsp/texlab/releases/tag/v5.0.0. It was working fine with 4.3.2 and this is the only change in the installed conda packages:

```diff
< texlab                    4.3.2                h8b8d39b_0    conda-forge
---
> texlab                    5.0.0                h8b8d39b_0    conda-forge
```

In both cases this is with:

```
chktex                    1.7.8                hcd874cb_0    conda-forge
```

texlab 5.0.0 works fine on Ubuntu (`hd9586b0_0`) with chktex 1.7.8 (`hcd874cb_0`) and Mac (`h08cba0f_0`) also with chktex 1.7.8 (`h9e318b2_0`).

There does not seem to be anything obviously related in the [changelog](https://github.com/latex-lsp/texlab/blob/master/CHANGELOG.md), nor any recent issues specific to Windows. The changeset is rather large so hard to narrow it down by just looking ([over 300 files](https://github.com/latex-lsp/texlab/compare/v4.3.2...v5.0.0)).

**Comment by krassowski** [comment]
Nothing suspicious in https://github.com/conda-forge/texlab-feedstock/pull/20 either.

**Comment by bollwyvl** [comment]
Yeah, sorry: maybe there's a way we can improve the conda-forge feedstock to test this earlier... I don't have a ready-to-hand headless LSP testing tool, a la `jupyter-kernel-test`...

**Comment by krassowski** [comment]
Just for reference this was the previous instance: https://github.com/jupyter-lsp/jupyterlab-lsp/issues/815.

**Comment by krassowski** [comment]
Closing as it is now passing as seen in https://github.com/jupyter-lsp/jupyterlab-lsp/pull/912 with version:

```
texlab                    5.4.0                h8b8d39b_0    conda-forge
```

**Comment by krassowski** [comment]
```
LaTeX :: diagnostics only appear if configured                        | FAIL |
```

Is now failing on all OSes:

```
texlab                    5.4.2                hd9586b0_0    conda-forge
```

It looks that the expectations need to be updated as it is now `Command terminated with space.` instead of `Command terminated with space. (chktex)`:

![image](https://user-images.githubusercontent.com/5832902/232322475-d8dcb8df-77f7-4a7f-8efc-2bde662333b0.png)

While release notes do not mention this, the git history shows that diagnostics were refactored between 5.4.0 and 5.4.2.
