### ISSUE TITLE
Delete jupyterlab cell Error

### ISSUE THREAD

**Issue by LDJ20210926** [jupyter-lsp/jupyterlab-lsp#906]
![image](https://user-images.githubusercontent.com/91396555/221329441-4ec29386-e3e8-4f9a-9066-6cdf8a91f541.png)

**Comment by krassowski** [comment]
Apologies that this was not addressed, but it is unlikely to be addressed without proper reproduction instructions. If the issue persists in the latest version, please reopen following the [bug report template](https://github.com/jupyter-lsp/jupyterlab-lsp/issues/new?assignees=&labels=&projects=&template=bug_report.md).
