### ISSUE TITLE
Duplicated settings panels

### ISSUE THREAD

**Issue by jase11** [jupyter-lsp/jupyterlab-lsp#925]
## Description

There are duplicate settings panels for this extension. One belongs to "**@krassowski 2.1.2**", another belongs to "**@jupyter-lsp 4.0.1**".
<img width="377" alt="chrome_1VfrwAEgKp (小)" src="https://user-images.githubusercontent.com/27488572/229788669-122cb468-2b6a-48bf-b84a-4aab3aecc3cd.png">

There is only "**@jupyter-lsp/jupyterlab-lsp**" but not  "@krassowski" in the stdout of the command `jupyter labextension list`

I found the `@krassowski` directories in `~/.jupyter/lab/user-settings` and `MY_CONDA_ENV_DIR/share/jupyter/labextensions` and deleted them. But the problem is still not solved.

## Expected behavior

I hope to see only one settings panel for this extension.

## Context

- Operating System and version: **CentOS 7, Linux kernal 3.10**
- Browser and version: **Chrome 111**
- JupyterLab version: **jupyterlab 3.6.3**
- Language server and version: **python-lsp-server 1.7.2**

<details><summary>Required: installed server extensions</summary>
<pre>
Config dir: ~/.jupyter   
    nbclassic disabled    
    - Validating nbclassic...    
      nbclassic  OK

Config dir: $MY_CONDA_ENV_DIR/etc/jupyter  
    jupyter_lsp enabled   
    - Validating jupyter_lsp...  
      jupyter_lsp 2.0.1 OK
    jupyter_resource_usage enabled      
    - Validating jupyter_resource_usage...     
      jupyter_resource_usage  OK 
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...      
      jupyter_server_fileid 0.6.0 OK    
    jupyter_server_ydoc enabled  
    - Validating jupyter_server_ydoc... 
      jupyter_server_ydoc 0.8.0 OK      
    jupyterlab enabled    
    - Validating jupyterlab...   
      jupyterlab 3.6.3 OK 
    nbclassic enabled     
    - Validating nbclassic...    
      nbclassic  OK

Config dir: /usr/local/etc/jupyter
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v3.6.3
$MY_CONDA_ENV_DIR/share/jupyter/labextensions
        jupyterlab-system-monitor v0.8.0 enabled OK (python, jupyterlab-system-monitor)
        jupyterlab-topbar-extension v0.6.1 enabled OK (python, jupyterlab-topbar)
        jupyterlab-notifications v0.4.1 enabled OK (python, jupyterlab-notifications)
        @jupyter-server/resource-usage v0.5.0 enabled OK (python, jupyter-resource-usage)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
        @jupyter-lsp/jupyterlab-lsp v4.0.1 enabled OK (python, jupyterlab-lsp)
</pre>
</details>

**Comment by krassowski** [comment]
This is not a bug. You must have the old version of this extension (2.1.2) installed _somewhere_ - maybe in a parent conda environment? Please uninstall the old version.

**Comment by krassowski** [comment]
Looking at the version, 2.x it seems that this was installed using `jupyter labextension install` so predating prebuilt packages. I would search `jupyter --paths` for a stale extension version and remove it manually.

**Comment by krassowski** [comment]
Closing as it appears to be a stale installation issue.
