### ISSUE TITLE
Configuring serverSettings for Pyright langserver 

### ISSUE THREAD

**Issue by baurzhan-konurbayev** [jupyter-lsp/jupyterlab-lsp#931]
## Description

Hi there,
Thanks for the awesome product first of all.
I am struggling with configuration for Pyright langserver. 
For some reason `serverSettings` parameter is not picked up.

Here is my `jupyter_server_config.py` file. Its located in `MY_CONDA_ENV/etc/jupyter/jupyter_server_config.py`
```python
c.LanguageServerManager.language_servers = {
    "pyright": {
        "argv": ["MY_CONDA_ENV/bin/pyright-langserver", "--stdio"],
        "languages": ["python"],
        "version": 2,
        "mime_types": ["text/python", "text/x-ipython"],
        "display_name": "pyright",
        "serverSettings": {
            "python.analysis.useLibraryCodeForTypes": True,
        },
    }
}

c.LanguageServerManager.autodetect = False
```

When I go to `Advanced Settings`, the configuration for lang servers is just empty
```json
    "language_servers": {}
```

When I manually edit settings and add this configuration piece, it works.
```json
{
    "language_servers": {
      "pyright": {
        "serverSettings": {
          "python.analysis.useLibraryCodeForTypes": true
        }
      }
    }
}
```

## Reproduce

Install pyright and nodejs together with Jupyterlab and LSP plugin.
Same steps as in description, plus disable suggestions from Kernel to make sure LSP is handling requests.
Try autocomplete, for example:
```python
import matplotlib

matplotlib.
```
Popup window won't be shown.

## Expected behavior

Autocomplete should work for `matplotlib` python package.

## Context

- Operating System and version:
Ubuntu 20.04.4 LTS

- Browser and version:
Edge  112.0.1722.48
- JupyterLab version:
```
jupyter-lsp               2.0.1              pyhd8ed1ab_0    /
jupyter_client            8.2.0              pyhd8ed1ab_0    /
jupyter_core              5.3.0           py310hff52083_0    /
jupyter_events            0.6.3              pyhd8ed1ab_0    /
jupyter_server            2.5.0              pyhd8ed1ab_0    /
jupyter_server_fileid     0.9.0              pyhd8ed1ab_0    /
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    /
jupyter_server_ydoc       0.8.0              pyhd8ed1ab_0    /
jupyter_ydoc              0.2.3              pyhd8ed1ab_0    /
jupyterlab                3.6.3              pyhd8ed1ab_0    /
jupyterlab-lsp            4.0.1              pyhd8ed1ab_0    /
jupyterlab_code_formatter 1.6.0              pyhd8ed1ab_0    /
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    /
jupyterlab_server         2.22.1             pyhd8ed1ab_0    /
jupyterlab_widgets        3.0.7              pyhd8ed1ab_0    /
```
- Language server and version:
pyright 1.1.303

<details><summary>Required: installed server extensions</summary>
<pre>
    jupyter_lsp enabled
    - Validating jupyter_lsp...
Package jupyter_lsp took 0.0107s to import
A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      jupyter_lsp 2.0.1 OK
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...
Package jupyter_server_fileid took 0.0025s to import
      jupyter_server_fileid 0.9.0 OK
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
Package jupyter_server_terminals took 0.0049s to import
      jupyter_server_terminals 0.4.4 OK
    jupyter_server_ydoc enabled
    - Validating jupyter_server_ydoc...
Package jupyter_server_ydoc took 0.0239s to import
      jupyter_server_ydoc 0.8.0 OK
    jupyterlab enabled
    - Validating jupyterlab...
Package jupyterlab took 0.0637s to import
      jupyterlab 3.6.3 OK
    jupyterlab_code_formatter enabled
    - Validating jupyterlab_code_formatter...
Package jupyterlab_code_formatter took 8.0691s to import
A `_jupyter_server_extension_points` function was not found in jupyterlab_code_formatter. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      jupyterlab_code_formatter 1.6.0 OK
    nbclassic enabled
    - Validating nbclassic...
Package nbclassic took 0.0000s to import
A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      nbclassic 0.5.5 OK
    notebook_shim enabled
    - Validating notebook_shim...
Package notebook_shim took 0.0000s to import
A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      notebook_shim  OK
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v3.6.3
/opt/conda/envs/ml-env/share/jupyter/labextensions
        jupyterlab-plotly v5.14.1 enabled OK
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        @jupyter-lsp/jupyterlab-lsp v4.0.1 enabled OK (python, jupyterlab-lsp)
        @jupyter-widgets/jupyterlab-manager v5.0.7 enabled OK (python, jupyterlab_widgets)
        @ryantam626/jupyterlab_code_formatter v1.6.0 enabled OK (python, jupyterlab-code-formatter)
</pre>
</details>

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
Paste the output from your browser JavaScript console replacing the text in here.

To learn how to open the developer tools in your browser:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser
If too many messages accumulated after many hours of working in JupyterLab,
consider refreshing the window and then reproducing the bug to reduce the noise in the logs.

</pre>
</details>

**Comment by krassowski** [comment]
The key is not `serverSettings` but `workspace_configuration`, see:

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/661b7435dd819be3ed71a968505a5b992af61aa6/python_packages/jupyter_lsp/jupyter_lsp/schema/schema.json#L165-L169

and our example configuration as used in integration tests:

https://github.com/jupyter-lsp/jupyterlab-lsp/blob/661b7435dd819be3ed71a968505a5b992af61aa6/atest/fixtures/jupyter_server_config.py#L1-L17

If changing the key to `workspace_configuration` is not enough I would advise ensuring that your `jupyter_server_config.py ` is picked up; to do so one could change the `display_name` of the server and see if this is reflected in UI after restart.

**Comment by krassowski** [comment]
Closing as answered, please reopen with more details if the above does not work.
