### ISSUE TITLE
file path auto completion add \ in path string

### ISSUE THREAD

**Issue by troubadour-hell** [jupyter-lsp/jupyterlab-lsp#935]
Hello! When I try to type in a file path, the auto-completion adds an \ before the last /, and it can't suggest the contents in this directory. Is there any way to make it not to add \ to my path? Thank you~
![1682511368991](https://user-images.githubusercontent.com/17946453/234571788-d4039822-f18c-407a-a105-b0df0c9ccfdd.jpg)
![1682511370687](https://user-images.githubusercontent.com/17946453/234571806-293c3faf-26c2-4e7b-9af0-fdb230d5e43c.jpg)

**Comment by krassowski** [comment]
Can you provide some more details? Which language server are you using? What version of IPython and ipykernel do you have installed? What happens if you disable LSP or kernel completions in the settings editor?

**Comment by troubadour-hell** [comment]
When I disable kernel completions, the auto-completion of the file path is not worked. While I disable LSP, the same things happen as I described above.
These are my ipython and lsp packages:
![image](https://user-images.githubusercontent.com/17946453/234579103-e0b2bf74-37cc-4579-ad34-15f524e5a59d.png)
![image](https://user-images.githubusercontent.com/17946453/234579159-66e62441-49e6-494e-82e1-51a6ab6d46d2.png)
The Code Completion setting is the default. 
Settings of jupyter-lsp is:
{
    "language_servers": {
        "julia-language-server": {
            "priority": 50,
            "serverSettings": {
                "julia.lint.run": true,
                "julia.lint.missingrefs": "none",
                "julia.lint.disabledDirs": [
                    "docs",
                    "test"
                ],
                "julia.lint.call": true,
                "julia.lint.iter": true,
                "julia.lint.nothingcomp": true,
                "julia.lint.constif": true,
                "julia.lint.lazy": true,
                "julia.lint.datadecl": true,
                "julia.lint.typeparam": true,
                "julia.lint.modname": true,
                "julia.lint.pirates": true,
                "julia.lint.useoffuncargs": true,
                "julia.completionmode": "qualify"
            }
        },
        "pylsp": {
            "priority": 50,
            "serverSettings": {
                "pylsp.configurationSources": [
                    "pycodestyle"
                ],
                "pylsp.plugins.flake8.config": null,
                "pylsp.plugins.flake8.enabled": false,
                "pylsp.plugins.flake8.exclude": [],
                "pylsp.plugins.flake8.executable": "flake8",
                "pylsp.plugins.flake8.filename": null,
                "pylsp.plugins.flake8.hangClosing": null,
                "pylsp.plugins.flake8.ignore": [],
                "pylsp.plugins.flake8.maxLineLength": null,
                "pylsp.plugins.flake8.indentSize": null,
                "pylsp.plugins.flake8.perFileIgnores": [],
                "pylsp.plugins.flake8.select": null,
                "pylsp.plugins.jedi.extra_paths": [],
                "pylsp.plugins.jedi.env_vars": null,
                "pylsp.plugins.jedi.environment": null,
                "pylsp.plugins.jedi_completion.enabled": true,
                "pylsp.plugins.jedi_completion.include_params": true,
                "pylsp.plugins.jedi_completion.include_class_objects": false,
                "pylsp.plugins.jedi_completion.fuzzy": false,
                "pylsp.plugins.jedi_completion.eager": false,
                "pylsp.plugins.jedi_completion.resolve_at_most": 25,
                "pylsp.plugins.jedi_completion.cache_for": [
                    "pandas",
                    "numpy",
                    "tensorflow",
                    "matplotlib"
                ],
                "pylsp.plugins.jedi_definition.enabled": true,
                "pylsp.plugins.jedi_definition.follow_imports": true,
                "pylsp.plugins.jedi_definition.follow_builtin_imports": true,
                "pylsp.plugins.jedi_hover.enabled": true,
                "pylsp.plugins.jedi_references.enabled": true,
                "pylsp.plugins.jedi_signature_help.enabled": true,
                "pylsp.plugins.jedi_symbols.enabled": true,
                "pylsp.plugins.jedi_symbols.all_scopes": true,
                "pylsp.plugins.jedi_symbols.include_import_symbols": true,
                "pylsp.plugins.mccabe.enabled": true,
                "pylsp.plugins.mccabe.threshold": 15,
                "pylsp.plugins.preload.enabled": true,
                "pylsp.plugins.preload.modules": [],
                "pylsp.plugins.pycodestyle.enabled": true,
                "pylsp.plugins.pycodestyle.exclude": [],
                "pylsp.plugins.pycodestyle.filename": [],
                "pylsp.plugins.pycodestyle.select": [],
                "pylsp.plugins.pycodestyle.ignore": [],
                "pylsp.plugins.pycodestyle.hangClosing": null,
                "pylsp.plugins.pycodestyle.maxLineLength": null,
                "pylsp.plugins.pycodestyle.indentSize": null,
                "pylsp.plugins.pydocstyle.enabled": true,
                "pylsp.plugins.pydocstyle.convention": null,
                "pylsp.plugins.pydocstyle.addIgnore": [],
                "pylsp.plugins.pydocstyle.addSelect": [],
                "pylsp.plugins.pydocstyle.ignore": [],
                "pylsp.plugins.pydocstyle.select": [],
                "pylsp.plugins.pydocstyle.match": "(?!test_).*\\.py",
                "pylsp.plugins.pydocstyle.matchDir": "[^\\.].*",
                "pylsp.plugins.pyflakes.enabled": true,
                "pylsp.plugins.pylint.enabled": false,
                "pylsp.plugins.pylint.args": [],
                "pylsp.plugins.pylint.executable": null,
                "pylsp.plugins.rope_completion.enabled": false,
                "pylsp.plugins.rope_completion.eager": false,
                "pylsp.plugins.yapf.enabled": true,
                "pylsp.rope.extensionModules": null,
                "pylsp.rope.ropeFolder": null
            }
        },
        "r-languageserver": {
            "priority": 50,
            "serverSettings": {
                "r.lsp.debug": true,
                "r.lsp.log_file": null,
                "r.lsp.diagnostics": true,
                "r.lsp.rich_documentation": true,
                "r.lsp.snippet_support": true,
                "r.lsp.max_completions": 200,
                "r.lsp.lint_cache": false,
                "r.lsp.link_file_size_limit": 16384
            }
        },
        "texlab": {
            "priority": 50,
            "serverSettings": {
                "rootDirectory": null,
                "build.executable": "latexmk",
                "build.args": [
                    "-pdf",
                    "-interaction=nonstopmode",
                    "-synctex=1",
                    "%f"
                ],
                "build.onSave": false,
                "build.outputDirectory": ".",
                "build.forwardSearchAfter": false,
                "forwardSearch.executable": null,
                "forwardSearch.args": [],
                "chktex.onOpenAndSave": false,
                "chktex.onEdit": false,
                "diagnosticsDelay": 300,
                "formatterLineLength": 80,
                "latexFormatter": "latexindent",
                "latexindent.local": null,
                "latexindent.modifyLineBreaks": false
            }
        }
    },
    "loggingConsole": "browser",
    "loggingLevel": "warn",
    "logAllCommunication": false,
    "setTrace": null
}

**Comment by krassowski** [comment]
What happens if you open ipython in terminal and attempt to complete the same path? Does it include the extra escaping slash too?

**Comment by troubadour-hell** [comment]
I opened ipython and found that auto-completion for the path is not working.  I removed all config files for ipython and found it worked well. For Jupyter, I restarted it and got correct path completion. But the suggestions gave different icons like:
![image](https://user-images.githubusercontent.com/17946453/234594605-05a10ddf-7e71-4527-a9da-730a1d3f92de.png)
 While I refresh the page, got wrong path again with old icons.

**Comment by troubadour-hell** [comment]
I find this:
https://github.com/python-lsp/python-lsp-server/blob/59856af9e7c3859d45133b79e02d1d7210fd50b3/pylsp/plugins/jedi_completion.py#L234
When I Removed "\\" from this line, it worked well. I'm not sure why it do this...
Thanks for you help!

**Comment by krassowski** [comment]
Cross-referencing https://github.com/python-lsp/python-lsp-server/issues/373

**Comment by i-aki-y** [comment]
@troubadour-hell @krassowski  This should be fixed in the recent release python-lsp-server 1.10.0.

**Comment by troubadour-hell** [comment]
> @troubadour-hell @krassowski This should be fixed in the recent release python-lsp-server 1.10.0.

I am using it. It seems working well. Thank you all!
