### ISSUE TITLE
Installed bash_language_server not detected / not usable

### ISSUE THREAD

**Issue by ackalker** [jupyter-lsp/jupyterlab-lsp#937]
## Description

Installed `bash-language-server` is not being detected by `jupyterlab-lsp` and so is not usable in either notebooks or file editors.

## Reproduce

1. Ensure that `jupyterlab-lsp`, `bash-language-server` (and `bash-kernel` if using Bash notebooks) are installed.
2. Start JupyterLab: `jupyter lab`.
3. Open a shell script file or notebook which uses the Bash kernel.
4. Observe the language server notification at the bottom of the window.

## Actual behaviour

On my setup, none of the language server features were working, and the indicator showed that a language server was missing.
My server log showed the line:

```
[I 2023-05-15 18:00:58.197 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
```

## Expected behavior

`bash-language-server` should be detected as installed and operational.

## Investigation

From looking at the source code, I found that https://github.com/jupyter-lsp/jupyterlab-lsp/blob/39ee7d93f98d22e866bf65a80f1050d67d7cb504/python_packages/jupyter_lsp/jupyter_lsp/specs/bash_language_server.py#L7 indicates `bin/main.js` as entry point.
However, in my version of `bash-language-server`, the entrypoint is now `out/cli.js`.
This is related to a reorganization of the file layout in `bash-language-server`, see the change in this commit: https://github.com/bash-lsp/bash-language-server/commit/56b959f2f30307d89ec8d1f2fc1088ab9bd3a6fb?diff=split#diff-da00458cdaeaea2314cb0e0101c85130593048072ada62de01727958c5d6ca37L10.

After manually changing `bash_language_server.py` in my installation with the correct path, `bash-language-server` works as expected.

I will create a PR with the change.

**Comment by krassowski** [comment]
Thank you! Should we check for both to support both old and new version?

**Comment by ackalker** [comment]
> Thank you! Should we check for both to support both old and new version?

How to do that? Have two language server spec files for the same language server? I'm honestly not too familliar with the codebase to be able judge the ramifications of this.

**Comment by jonasbb** [comment]
My installation has this symlink inside the `node_modules` folder. `node_modules/.bin/bash-language-server -> ../bash-language-server/bin/main.js`. It gets updated to the correct `out/cli.js` file when installing v4 of bash-language-server. Maybe that is a more stable place as the script entry point.

**Comment by krassowski** [comment]
Just to document, this change happened in in bash-lsp 4.3.2
https://github.com/bash-lsp/bash-language-server/compare/server-4.3.0...server-4.3.2
