### ISSUE TITLE
NamedTuple not hinting its arguments

### ISSUE THREAD

**Issue by OnyxianSoul** [jupyter-lsp/jupyterlab-lsp#945]
## Description
When requesting the arguments for the instantiation of a typing.NamedTuple, the arguments listed during the definition of that NamedTuple arent listed.

## Example images
![imagen](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/74385137/509252e2-f492-4b81-8485-b5a7ace2d6e7)
![imagen](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/74385137/fdea80db-a87b-46ec-9c4e-33f74c22e0ff)

## Reproduce

1. Define a typing.NamedTuple, ex: `Example1 = typing.NamedTuple('Example1', first_arg=int, second_arg=int)`
2. Write the name of that tuple() to begin creating the tuple, ex: `Example1()`
3.  With the cursor between the parenthesis, begin writting the name of one of the parameters, and use tab. You'll see that the construction parameters are nowhere to be found. ex: Example(fi)

## Expected behavior
The construction arguments of NamedTuple, should be in the list of suggestions, like it happens when using collections.namedtuple
![imagen](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/74385137/2ef57f8d-cc7e-4eef-88ed-0453f32b3bbd)

## Additional info
Interestingly enough, if using shift tab to request the signature, the correct arguments are shown for typing.NamedTuple aswell:
![imagen](https://github.com/jupyter-lsp/jupyterlab-lsp/assets/74385137/b2cb972e-edcc-405a-aefb-76249a17a2df)

**Comment by krassowski** [comment]
This is an issue in the respective language server used by kaggle, not the jupyter(lab)-lsp itself. Do you know if that is pylsp or pyright?

**Comment by krassowski** [comment]
Closing as this is likely an issue in a language server, not in this extension.
