### ISSUE TITLE
No provider for: @jupyter-lsp/jupyterlab-lsp:ILSPAdapterManager

### ISSUE THREAD

**Issue by skbitsp** [jupyter-lsp/jupyterlab-lsp#977]
Hi, facing a weird issue with importing an instance of ILSPAdapterManager in our extension. I have tried with LSP versions 4.2.0 and 3.10.2, both.

Steps: 

1. importing: `import {ILSPAdapterManager} from '@jupyter-lsp/jupyterlab-lsp';`
2. Putting it in requires and then in activate function of the extension and then using it:

```
const extensions = [{
  id: '<redacted>',
  requires: [ILSPAdapterManager],
  activate: async (app, adapterManager) => {
      adapterManager.registerAdapterType(...)
  }
```

It fails saying: `index.es6.js:2289 Error: No provider for: @jupyter-lsp/jupyterlab-lsp:ILSPAdapterManager.`, similarly in the setup for 3.x version of LSP, it fails with: `No provider for: @krassowski/jupyterlab-lsp:ILSPAdapterManager`.

On putting a breakpoint there, I can see that a corresponding entry is present for these Tokens:

<img width="656" alt="Screenshot 2023-09-07 at 7 47 47 PM" src="https://github.com/jupyter-lsp/jupyterlab-lsp/assets/142968737/bde43b81-d5ea-4037-a988-600ec13ee394">

I am assuming the token its asking for and the token present are different "instances" even though the "name" of the tokens is the same. Any ideas?

....

One more thing is, I was able to get it working in a specific setup (by chance) with `pip install jupyterlab-lsp==3.10.2` and having a dependency of lsp extension 4.2.0 in my project. Basically jupyterlab extension version was 4.2.0, but the python version was 3.10.2. In this specific combination using `import {ILSPAdapterManager} from '@jupyter-lsp/jupyterlab-lsp`, the extension comes up! But that leads to double instances of the extension, hence this is not a clean solution.

**Comment by krassowski** [comment]
For the JS version you may want to try something like:

```json
{
"sharedPackages": { 
   "@jupyter-lsp/jupyterlab-lsp": { 
     "bundled": false, 
     "singleton": true, 
     "strictVersion": true
   } 
 }
}
```

in your `package.json`. See: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#deduplication-of-dependencies

**Comment by krassowski** [comment]
Another thing to try if the above does not help: can you require `ILSPExtension` token? If so, this could be a bug in other tokens having mismatching IDs vs plugins that provide them.

**Comment by skbitsp** [comment]
I added that shared packages, didn't help. Also, the other tokens like ILSPExtension, etc. are also not found.
As a hack, tried setting the instance to a global variable in `adapter_manager.ts` inside activate function: 
```
      let wam = new WidgetAdapterManager(shell);
      console.log("Inside LSP. Setting the adatper manager");
      console.log(wam)
      window.lspAdapterManager = wam;
      return wam;
```

Then in my extension reading it using `window.lspAdapterManager`. Both the instances are same.. 
<img width="314" alt="Screenshot 2023-09-08 at 3 30 43 PM" src="https://github.com/jupyter-lsp/jupyterlab-lsp/assets/142968737/f91f4cef-bf18-4685-9052-a8e1120cd23b">

The registeration (adapterManager.registerAdapterType) also goes through but the extension doesn't come up! :(

**Comment by skbitsp** [comment]
The way I am installing is the extension from local is: 
1. Inside both the python packages `jupyter_lsp` and `jupyterlab_lsp`, i am doing `pip install .` 
2. Under `packages/jupyterlab-lsp`, I have done a `yarn link` and linked it to my swb extension.

---Ideally the above steps should have installed the extension, but the changes were not coming in the application's node_modules, so the 3rd step---

3. Did `jupyter labextension install .` 

Do you think these steps might lead to any duplication of the extension installed and the token which is in my extension vs which is getting registered are different? 🤔

**Comment by skbitsp** [comment]
Put debugger points and was able to understand that the issue is that it sets the language server here (the Private.setLanguageServerManager in connection_manager.ts): 

(notice the file location)

<img width="1131" alt="Screenshot 2023-09-11 at 2 57 03 PM" src="https://github.com/jupyter-lsp/jupyterlab-lsp/assets/142968737/2057c190-47ce-4a2d-b339-9d0a06fce48f">


Whereas the `Private.getLanguageServerManager()` is called here (inside my extension's node_modules): 
<img width="1175" alt="Screenshot 2023-09-11 at 2 58 23 PM" src="https://github.com/jupyter-lsp/jupyterlab-lsp/assets/142968737/ef408000-d86e-45e6-bd77-90f73837eb46">

Because of the mismatch of these file locations, its not able to get the language server manager when its invoked. How to install the extension and also use it as a dependency in my local extension without this separation of concerns 🤔

**Comment by krassowski** [comment]
As you correctly notice you extension ships a copy of jupyterlab-lsp but it should not. As previously mentioned, configuring `sharedPackages` within `jupyterlab` stanza of `package.json` should ensure that webpack resolves it correctly. I know that you already tried that, but seeing my comment now it may have not been obvious that it needs to go within the `jupyterlab` stanza. Can you give it another go?

**Comment by krassowski** [comment]
As for the installation, I do not see why you would use `yarn link`, unless you are forking this extension. Normally it would be just adding it to the dependencies. On `jupyter labextension install` - are you using it to install your own extension, or jupyterlab-lsp? I would say it should never be used except for deployment of source extensions. For development of your own extension `jupyter labextension develop` is appropriate. For dependencies, these should not be explicitly installed but handled by the package manager of choice (jlpm/yarn/npm) and configured in `package.json` for webpack to de-duplicate. If you had indeed forked `jupyterlab-lsp` locally for some reason, installing a second copy via `pip` would indeed lead to two different copies.

This is about as much as I can help without more detailed info or reproducer.

**Comment by krassowski** [comment]
You should not need to do that. While they are not exported from `index.ts`, these are themselves all exported symbols, so you should be able to access them from `lib`:

```js
import {WidgetAdapterManager} from '@jupyter-lsp/jupyterlab-lsp/lib/adapter_manager';
```

This is of course not ideal, which is why it was reworked for JupyterLab 4/jupyterlab-lsp 5.0.

Does this help?

**Comment by skbitsp** [comment]
I tried that only initially, but it was leading to same issue of file duplication. The two locations: 
```
webpack://jupyterlab/application-top/node_modules/@jupyter-lsp/jupyterlab-lsp/lib/connection_manager.js
webpack://jupyterlab/application-top/darwin-tabular-analysis/node_modules/@jupyter-lsp/jupyterlab-lsp/src/connection_manager.ts
```
The `Private.setLanguageServerManager()` was getting called in `connection-manager.js` and the getter is called in `connection-manager.ts`.

Putting the exports solved this issue. But the issue was solved for a **specific environment** of python version 3.10 and other version `4.2.0` (which I cloned in my local and made these export changes on top of and linked to my swb extension). 

If I use just one of the versions, then I am unable to bypass the issue of `No provider for: @jupyter-lsp/jupyterlab-lsp:ILSPAdapterManager`, which brings us to the starting of this issue thread 😄. 

P.S. can we export these in the Open source version of 4.x? I can raise the PR and you can help releasing a corresponding version, then I won't have to make a local copy and export these statements.

**Comment by krassowski** [comment]
Feel welcome to open a PR.

Regarding `ILSPAdapterManager`/de-duplication:
- ensure `sharedPackages` setting gets picked up from your package.json; you can test it by putting a dependency on fake version of `@jupyter-lsp/jupyterlab-lsp` in `dependencies`, say `^100.0` and enabling `strictVersion`.

**Comment by skbitsp** [comment]
Great! I was able to resolve the issue :) Basically I was doing an additional pip install of jupyterlab-lsp. But still had to export the classes.

Raised this PR: https://github.com/jupyter-lsp/jupyterlab-lsp/pull/980. Would require your help in merging it and releasing a version we can use. 

Also, can we change the configuration settings (like Automatic hover) while deploying?

Thanks.

**Comment by skbitsp** [comment]
Hi, I guess the PR got missed. Would need your help in getting this merged :) - https://github.com/jupyter-lsp/jupyterlab-lsp/pull/980

**Comment by krassowski** [comment]
Checking back, did https://github.com/jupyter-lsp/jupyterlab-lsp/pull/980 fix the issue for you @skbitsp?

**Comment by krassowski** [comment]
Closing as resolved, feel welcome to open any follow-up issues.
